filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/apache2/*.log
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

output.logstash:
  hosts: ["localhost:5044"]

setup.kibana:
  host: "http://localhost:5601"

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644

setup.ilm.enabled: auto
